In [6]:
#分组聚合
#df.groupby('分组的字段‘）['聚合的字段'].聚合函数（）
import pandas as pd
df = pd.read_excel('students.xlsx')
print(df['id'].isna().sum())
df.dropna(subset=['id'], inplace=True)
print(df['id'].isna().sum())
df['id'] = df['id'].astype('int64')
df

1
0

   id  姓名 性别  年龄  地址
1   1  张三  男  20  江苏
2   2  里斯  女  22  江苏

In [15]:
#分组
df.groupby('id').groups#查看所有分组
df.groupby('id').get_group(1)#查看具体的某个分组数据
df2 = df.groupby('id')[['id']].mean()
df2['id'] = df2['id'].round(0)
df2

     id
id
1   1.0
2   2.0